"""add link field

Revision ID: 1009b65ac3a1
Revises: 28e8c2a1a048
Create Date: 2025-01-31 18:42:57.919155

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1009b65ac3a1'
down_revision: Union[str, None] = '28e8c2a1a048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
