"""make google id str

Revision ID: 6f9c1e0b9cc3
Revises: abe094ef1255
Create Date: 2025-02-24 18:21:55.361256

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f9c1e0b9cc3'
down_revision: Union[str, None] = 'abe094ef1255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'google_subject_id',
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'google_subject_id',
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False
        )
    # ### end Alembic commands ###
